# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76d1fe0edf7046e7e4238e050929392482188a2850ff621474d99cc1cbdb2943989e8480997f2d28a95369548f45144d937a82550156f6819188aaf8ecb036e5

test:
  secret_key_base: 9f3256bfc20a76d98cd8f39304b75813f5a5d35538030636d6296a170461c2666173469c19f9bf80e1c9ab03d9cc92a1401c0f07db2de40aa17b6908ca559e6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
